### PR TITLE
initial 2fa Registration method

### PR DESCRIPTION
**Pull request by coolzoom**

### CODE REVIEW

**Comment by masterking32** [comment]
Hey,
Thank you ...
But that's not working for TC and I think that would be better to add it as an option to allow the players to enable it or not.
However, that's good.
But let me try it too :D

**Comment by coolzoom** [comment]
Hey man, oh yes you are right, it only works for a few cores, not TC, because I haven't try TC 2FA registration, not sure how it works probably similar. I will check to see how TC works later on.

**Comment by coolzoom** [comment]
great, thanks man

**Comment by kaneit** [comment]
Does this work for TC yet?

**Pull request closed without merging**
